# Generated by Django 4.1.13 on 2024-06-17 16:46

from django.db import migrations, models
import django.db.models.deletion
import generic_app.generic_models.fields.XLSX_field
import generic_app.generic_models.upload_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMerge',
            fields=[
                ('is_calculated', generic_app.generic_models.upload_model.IsCalculatedField(default=False)),
                ('calculate', generic_app.generic_models.upload_model.CalculateField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('mailmerge_docx', models.FileField(max_length=300, upload_to='submodels/MailMerge/mailmerge_docx/')),
                ('upload_template', generic_app.generic_models.fields.XLSX_field.XLSXField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/upload_template/')),
                ('upload_data', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/upload_data/')),
                ('zip_docx', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/zip_docx/')),
                ('zip_pdf', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/zip_docx/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(default='')),
                ('docx_document', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/docx_document/')),
                ('pdf_document', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='submodels/MailMerge/pdf_document/')),
                ('mail_merge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailMerge.mailmerge')),
            ],
        ),
    ]
